SELECT ID,
CASE 
    WHEN A.QUAR = 1 THEN 'CRITICAL'
    WHEN A.QUAR = 2 THEN 'HIGH'
    WHEN A.QUAR = 3 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM (
    SELECT ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUAR
    FROM ECOLI_DATA
) AS A
ORDER BY A.ID