SELECT CAR_ID,
    CASE
    WHEN CAR_ID IN (SELECT CAR_ID
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                   WHERE "2022-10-16" BETWEEN START_DATE AND END_DATE) THEN '대여중'
    ELSE '대여 가능'
    END AS AVAILABILITY

# CASE 
#     WHEN DATE_FORMAT(END_DATE, "%YY-%mm-%dd") < "2022-10-16" THEN '대여 가능'
# END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE DATE_FORMAT(START_DATE, "%YY-%mm-%dd") >= "2022-10-15"
GROUP BY CAR_ID
HAVING MAX(END_DATE)
ORDER BY CAR_ID DESC;

